### ISSUE TITLE
Step 5 of the read me is unclear

### ISSUE THREAD

**Issue by ArieVanE** [infoportugal/wagtail-modeltranslation#12]
In step 5 of the introduction you write:

In order to update pages url_path field use "set_translation_url_paths" instead of original "set_url_paths"

It's unclear to me what you mean with this. Where should I do this? Could you provide an example or so?

**Comment by rmartins90** [comment]
"set_url_paths" is an wagtail management command that updates url_path field on db that wagtail uses in order to construct urls for each node. This is done automatically when you create pages, but eventually you need to update that manually.
"set_translation_url_paths" is a substitute for the original one, you should use it instead if you're using modeltranslation, generally you need to worry about that.

**Comment by ArieVanE** [comment]
I'm quite new to wagtail and django-model-translation. Could you give me an example of this please?

**Comment by rmartins90** [comment]
I believe that you've found the solution.

**Comment by SalahAdDin** [comment]
:+1: for and example.
