### ISSUE TITLE
sync_page_translation_fields works only on Page model, not subclass

### ISSUE THREAD

**Issue by pyMan** [infoportugal/wagtail-modeltranslation#186]
The `sync_page_translation_fields` command creates the lang-fields only for the `Page` model. It should work on all its subclasses.

Its `get_page_model` method now does:

`return [x for x in models if x is Page]`

it should do instead:

`return [x for x in models if issubclass(x, Page)]`

**Comment by dmarcelino** [comment]
Hi @pyMan,

That's by design, [sync_page_translation_fields](http://wagtail-modeltranslation.readthedocs.io/en/latest/management%20commands.html#the-sync-page-translation-fields-command) only applies to `Page` because it's a *necessary evil* for wagtail-modeltranslation 0.8+ to work at all. To handle `Page` subclasses you can use Django migrations or django-modeltranslation's [sync_translation_fields](http://django-modeltranslation.readthedocs.io/en/latest/commands.html#the-sync-translation-fields-command). I recommend the former.

**Comment by dmarcelino** [comment]
Please reopen if you feel this isn't solved.

**Comment by pyMan** [comment]
How can I use that command it if I cannot add `modeltranslation` since it doesn't support StreamField?

**Comment by dmarcelino** [comment]
@pyMan, `django-modeltranslation` is a dependency of `wagtail-modeltranslation` so it's already installed in your env. To use `sync_translation_fields` you only need to add `'modeltranslation',` to your `INSTALLED_APPS` (I suggest you add it below `'wagtail_modeltranslation'` apps).

Is there any reason for you not to use `makemigrations` / `migrate` as suggested in the [Quick Start](https://github.com/infoportugal/wagtail-modeltranslation#quick-start)?

**Comment by pyMan** [comment]
@dmarcelino If you add `django-modeltranslation` to the `INSTALLED_APPS` before or after `wagtail_modeltranslation` you get this:
`django.core.exceptions.ImproperlyConfigured: StreamField is not supported by modeltranslation`

I run `makemigrations` forcing only the default language begin defined in `LANGUAGES` because my application will be used on more servers as separate projects and each one will have its set of languages.

In this way I have the migration files with one language (always present) and I can easily migrate databases without creating unnecessary lang-fields. The necessary fields per database will be created with `sync_translation_fields`. I'll find a way to execute it.

Thanks

**Comment by dmarcelino** [comment]
@pyMan, you seem to have hit the same issue I hit back in  #139 but for me the following setup worked:

> ```
>     # django.contrib apps
>     ...
> 
>     'wagtail_modeltranslation',  # i18n for wagtail (must come before modeltranslation)
>     'modeltranslation',  # i18n for models
> 
>     # Admin
>     'django.contrib.admin',
> 
>     # third party apps
>     ...
> 
>     # project apps
>     ...
> ```

I'm still using this setup with `django-modeltranslation`, `wagtail-modeltranslation` and `StreamField` successfully.

Regarding migrations, gotcha, that makes sense.

It may be worth it for us to proxy `sync_translation_fields` on `wagtail-modeltranslation`, in the same manner we proxy `update_translation_fields` (see [update_translation_fields.py](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/management/commands/update_translation_fields.py)). I'll gladly review such PR.

**Comment by pyMan** [comment]
@dmarcelino you are right. If I move `django.contrib.admin` after `*modeltranslation` it works.

About proxying: `sync_page_translation_fields' is already proxed to 'sync_translation_fields' in the same way of `update_translation_fields`. It's only filtering out from the registered models for translation all models but `Page`.

It should be enough to do what I suggested in the original post of this issue and I do not see any valid reason to not do so. It's the same _necessary evil_ you talked about. There are different approaches for  [translating content with wagtail](http://docs.wagtail.io/en/v2.0/advanced_topics/i18n/index.html#translating-content), but if I choose wagtail_modeltranslation I expect all Page models are treated in the same manner. It's a idea of mine anyway.

**Comment by dmarcelino** [comment]
@pyMan, good to hear it worked for you.

The reason for `sync_page_translation_fields` being limited to `Page` model is so Django migrations can be used for the remaining models. `wagtail-modeltranslation` can't handle `Page` through Django migrations because it belongs to the Wagtail app and that's why `sync_page_translation_fields` came to be, but all `Page` subclasses created by the user can, and usually should, be handled by Django migrations. For those not using Django migrations, your case for example, `sync_translation_fields` exists and does the work. See the discussion on PR  #150 about `sync_page_translation_fields`.

**Comment by pyMan** [comment]
got it :)
