### ISSUE TITLE
ValidationError on deleting a Root's child page

### ISSUE THREAD

**Issue by pyMan** [infoportugal/wagtail-modeltranslation#187]
I get a ValidationError because the lang-fields`title`, `slug`, etc. of the root page are null/blank. Their value is checked because when deleting a page its parent is being saved to update the `numchild` field.

Maybe the `sync_page_translation_fields` command may initialize the fields.

Version 0.8.1

**Comment by dmarcelino** [comment]
@pyMan, did you go through the [Quick Start](https://github.com/infoportugal/wagtail-modeltranslation#quick-start)? Some things have changed since 0.6, it's worth checking it out.

From what you're describing you probably need to run [update_translation_fields](http://wagtail-modeltranslation.readthedocs.io/en/latest/management%20commands.html#the-update-translation-fields-command) to populate translation fields with pre-existing values.

**Comment by dmarcelino** [comment]
Please reopen if you feel this isn't solved.

**Comment by pyMan** [comment]
I see `update_translation_fields` only updates the lang-fields of the default language, so the problem still stays.
