### ISSUE TITLE
Upgrading 0.6 -> 0.8

### ISSUE THREAD

**Issue by dwasyl** [infoportugal/wagtail-modeltranslation#192]
The new data model seems much more efficient than the old structure of translations existing on each page type table, however, upon upgrading to 0.8 and running `sync_page_translation_fields` and `update_translation_fields`, I seem to have lost my exist translations for page titles/slugs.

Is there any easy way to migrate this data, or do I have to put together my own data migration?

**Comment by dmarcelino** [comment]
Hi @dwasyl,

Short answer: yes, I'm afraid, you'll have to put together your own data migration.

Long answer: in 0.6 translation page titles and slugs lived in the subclasses tables. In 0.8 translation titles and slugs live in `Page` model (`wagtailcore_page` table) to avoid calls to `.specific` / SQL joins. More details in PR #150. To upgrade my course of action would be something like:

1. Upgrade wagtail-translation to v0.8
2. Run `sync_page_translation_fields` to create the translation titles and slugs in `wagtailcore_page` table
3. Run your own script/command to copy translation fields from subclasses tables to `wagtailcore_page` table
4. Run `makemigrations`, `migrate` and `update_translation_fields`.

If you could make such data migration as a generic command that could be merged into wagtail-modeltranslation code, it would be great!

**Comment by dwasyl** [comment]
Thanks @dmarcelino. I will see what I can do - would be happy to even take a first pass.

I'm having trouble making the old `slug_` fields available to me after I've run `sync_page_translation_fields`.

I'll keep trying. This is definitely a significant issue for anyone else that has been using this app.

**Comment by dmarcelino** [comment]
I think the problem may be that after upgrading to 0.8 the new Django models no longer include the translations fields in the subclasses (since these moved to `Page`). To be able to do this in Python I believe you would need to load the *historical* models, something akin to what's done on this [SO answer](https://stackoverflow.com/a/39743581/4249576). Otherwise you'll probably need to use SQL.

I also forgot to mention that a good starting point for such command is [update_translation_fields.py](https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/management/commands/update_translation_fields.py) ([docs](http://django-modeltranslation.readthedocs.io/en/latest/commands.html#the-update-translation-fields-command)) which copies existing untranslated values to the default language.

An alternative for the data migration is to do it while using v0.6. In v0.6 you still have access to existing translations, so you can create the necessary translation fields in `wagtailcore_page` table and populate them. Upgrading to v0.8 afterwards should keep all migrated translations.

Good luck @dwasyl and I hope I didn't confuse you.

**Comment by dwasyl** [comment]
Thanks @dmarcelino, yes with a bit of effort it was very easy in SQL as opposed to Django. There really should be a tool for this, so I may see if I can spend a bit of time on it, but dropping to SQL simplifies the matter greatly.
