### ISSUE TITLE
Page titles in the admin view show up in the preferred language of the last editor

### ISSUE THREAD

**Issue by TheoChevalier** [infoportugal/wagtail-modeltranslation#271]
### Issue Summary

When using Wagtail in a different language, and after editing pages, all other users of the Wagtail instance will see the page titles in this language in the admin panel.

### Steps to Reproduce

1. Change your Wagtail language preferences to French from `account/language_preferences/`
2. Edit a CMS page that is translated in French (and has at least a translated title)

**Actual**: All CMS users will see the page title in French in the navigation tree

**Expected**: The page title is in English. Changing language preferences for one user shouldn’t impact other CMS users.

Here’s a screenshot from a colleague seeing the page title in French:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1068783/77499751-2ce5a100-6e10-11ea-8a8b-7407059cf720.png">

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: No

### Technical details
* wagtail-modeltranslation version: `0.10.7`
* Python version: `3.7`.
* Django version:  `2.2.11`.
* Wagtail version: `2.6.3`.
* Browser version: Firefox Nightly 76

**Comment by DiogoMarques29** [comment]
Hello @TheoChevalier 
`django-modeltranslation`, the 'mother' package of this repo, duplicates fields for all languages.
For example, when registering field `title` it will create `title_pt` and `title_en` (in case only PT and EN are languages of the website). Every time a update is made to a page, the default field `title` will be updated with the value of the update. If is an update to `title_pt`, `title` will be updated to with it's value.
The problem is that all wagtail interface always calls `page.title` without activating a language, so it will allways show the value of the default field.
I believe a middleware to activate a specific language only for admin interface solves the problem.
Cheers
