### ISSUE TITLE
Image rendering problem

### ISSUE THREAD

**Issue by rodrigo-capyba** [infoportugal/wagtail-modeltranslation#292]
Hi, i'm having a problem with image rendering.

I'm using:
- wagtail==2.9
- wagtail-modeltranslation==0.10.13

The problem is the image isn't rendering if its registered for translation. It works fine if i'm not using the translation.

_models.py_:
```
class HomePage(Page):
    intro_title = models.CharField(max_length=16, verbose_name="Título")
    intro_body = models.CharField(max_length=64, verbose_name="Corpo")
    intro_background = models.ForeignKey(
        "wagtailimages.Image", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Imagem de fundo"
    )
```

_translation.py_:
```
@register(HomePage)
class HomeTranslation(TranslationOptions):
    fields = (
        "intro_title",
        "intro_body",
        "intro_background",
    )
```

_home_page.html_:
```
{% load wagtailimages_tags %}

{% block content %}
	<h1>{{ self.title }}</h1>

	{% image self.intro_background original as intro_bg %}
	<div style="background-image:url({{ intro_bg.url }});">
		<h2>{{ self.intro_title }}</h2>
		<p>{{ self.intro_body }}</p>
		<p>{{ self.intro_background }}</p>
	</div>
{% endblock %}
```
Note: {{ self.intro_background }} renders None

**Comment by DiogoMarques29** [comment]
Hello @rodrigo-capyba 

I'm not able to reproduce your problem. I've created a branch on demo repo, check [here](https://github.com/infoportugal/wagtail-modeltranslation-demo/tree/issue_292). running without problems.

Please note that I added `url(r'', include(wagtail_urls)),` to `i18n_patterns` instead of normal `urlpatterns` so that we can test different languages only by changing the URL `http://127.0.0.1:8000/en/`or `http://127.0.0.1:8000/pt/`

**Comment by rodrigo-capyba** [comment]
Hi @DiogoMarques29 
After your comment i tried again and it seems to be working fine.
I don't know what happened, didn't changed a thing. 
Thank you.
