### ISSUE TITLE
Copying content of streamfields fails with 500

### ISSUE THREAD

**Issue by grillr** [infoportugal/wagtail-modeltranslation#39]
**Copy content of streamfields**

Recently I've noticed that the function to copy content of a streamfield does not work in my project. In the traceback (see attached) I saw that the request failed with the error code **500**.
The streamfield is registered for translation and in the admin interface the streamfields for every language are visible. When one of the language buttons are clicked, the request fails and nothing happens.

Is this a bug or could be something wrong with my setup?

Additionally, it would be nice to hide these buttons if the streamfield is not registered for translation.

Using:
- Django 1.8.5
- wagtail 1.1
- wagtail-modeltranslation 0.3.2

```
Request Method: GET
Request URL: /admin/pages/5/edit/copy_translation_content?origin_field_name=page_de&target_field_name=page_content&serializedOriginField=%5B%5D HTTP/1.1" 500 15117

ERROR django.request handle_uncaught_exception(256): Internal Server Error: /admin/pages/5/edit/copy_translation_content
Traceback (most recent call last):
  File "<PATH_TO_VIRTUALENV>/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<PATH_TO_VIRTUALENV>/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "<PATH_TO_VIRTUALENV>/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "<PATH_TO_VIRTUALENV>/lib/python2.7/site-packages/wagtail_modeltranslation/wagtail_hooks.py", line 75, in return_translation_target_field_rendered_html
    q_data, {}, target_field_name)
  File "<PATH_TO_VIRTUALENV>/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 135, in value_from_datadict
    count = int(data['%s-count' % prefix])
  File "<PATH_TO_VIRTUALENV>/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'page_content-count'"
```

**Comment by fdemmer** [comment]
we also sent this to the wagtail mailing list (https://groups.google.com/forum/#!topic/wagtail/XYb6QQaiZk4), but it turns out this is really a wagtail-modeltranslation issue. here are my findings summarized:

this are the GET parameters sent by the ajax request upon clicking a "copy content" button:
- origin_field_name: "page_de"
- target_field_name: "page_content"
- serializedOriginField: [] (an empty list!)

Looking at the DOM, this is the button for copying the "DE" content:
<button class="translation-field-copy" current-lang-code="page_content" data-lang-code="page_de">de</button>

`copy_stream_fields.js` creates the buttons based on the stream fields existing in the DOM and uses simple plitting at "_" to determine the `fieldName` and `fieldLang`. In our model the streamfield is called `page_content`. so the "_" in the fieldname breaks the button creation code.
